pp6calculator: FourVector Class Reference
FourVector Class Reference
Four Vector Class.
#include <FourVector.hpp>
Public Types
enum FourVectorType { SPACELIKE, TIMELIKE, NULLVECTOR }
Public Member Functions
FourVector ()
Default Constructor.
FourVector (double a0, double a1, double a2, double a3)
Initalised Constructor.
FourVector (const FourVector &other)
Copy Constructor.
void boost_z (const double &v)
Boost FourVector in z direction.
~FourVector ()
Default destructor.
double getA0 () const
get a0
double getA1 () const
get a1
double getA2 () const
get a2
double getA3 () const
get a3
void setA0 (double a0_in)
set a0 component
void setA1 (double a1_in)
set a1 component
void setA2 (double a2_in)
set a2 component
void setA3 (double a3_in)
set a3 component
double getInterval () const
Get the four vector interval.
ThreeVector getThreeVector () const
Get the three vector of the four vector.
void setThreeVector (const ThreeVector &newVector)
Set the three vector component.
FourVector::FourVectorType getFourVectorType () const
FourVector & operator+= (const FourVector &rhs)
Add another FourVector component wise.
FourVector & operator-= (const FourVector &rhs)
FourVector & operator= (const FourVector &rhs)
Friends
FourVector operator+ (const FourVector &lhs, const FourVector &rhs)
FourVector operator- (const FourVector &lhs, const FourVector &rhs)
std::ostream & operator<< (std::ostream &stream, const FourVector &v)
Detailed Description
Four Vector Class.
A class to contain a reletevistic four vector as well as providing mathmatical opperations the spacelike component is stored as a ThreeVector object
Definition at line 13 of file FourVector.hpp.
Constructor & Destructor Documentation
FourVector::FourVector (double a0, double a1, double a2, double a3)
Initalised Constructor.
Parameters
a0 a0
a1 a1
a2 a2
a3 a3
Definition at line 7 of file FourVector.cpp.
 : a0_(a0_in), spaceLike_(a1_in, a2_in, a3_in), interval_(0)
 {
     calculateInterval();
 }
FourVector::FourVector (const FourVector & other)
Copy Constructor.
Parameters
other FourVector to Copy
Definition at line 13 of file FourVector.cpp.
 : a0_(other.getA0()), spaceLike_(other.spaceLike_), interval_(other.getInterval())
 {}
Member Function Documentation
void FourVector::boost_z (const double & v)
Boost FourVector in z direction.
Boosts the four vector object into a frame at \(v \) velocity in the z axis, using natural units
Parameters
v velocity in natural units
Definition at line 18 of file FourVector.cpp.
References getA0(), getA3(), setA0(), and setA3().
 {
     double a0Prime = lorentzGamma(v)*(getA0() - v*getA3());
     //a1 is unchanged
     //a2 is unchanged
     double a3Prime = lorentzGamma(v)*(getA3() - v*getA0());
     setA0(a0Prime);
     setA3(a3Prime);
 }
double FourVector::getInterval () const
Get the four vector interval.
Returns the interval of the four vector ie \(A_{\mu}A^{\mu} = \text{interval}\)
Returns
interval
Definition at line 79 of file FourVector.cpp.
 {
     return interval_;
 }
ThreeVector FourVector::getThreeVector () const
Get the three vector of the four vector.
Returns \(\vec{v}\) from \(A^{\mu}=(A^0,\vec{v})\)
Returns
ThreeVector
Definition at line 84 of file FourVector.cpp.
 {
     return spaceLike_;
 }
FourVector & FourVector::operator+= (const FourVector & rhs)
Add another FourVector component wise.
Parameters
rhs Other FourVector
Definition at line 109 of file FourVector.cpp.
References getA0(), getA1(), getA2(), getA3(), and setA0().
 {
     setA0(getA0() + rhs.getA0());
     setA0(getA1() + rhs.getA1());
     setA0(getA2() + rhs.getA2());
     setA0(getA3() + rhs.getA3());
     calculateInterval();
     return *this;
 }
void FourVector::setThreeVector (const ThreeVector & newVector)
Set the three vector component.
Sets \(\vec{v}\) from \(A^{\mu}=(A^0,\vec{v})\)
Parameters
newVector \(\vec{v}\)
Definition at line 89 of file FourVector.cpp.
 {
     spaceLike_ = newVector;
     calculateInterval();
 }
The documentation for this class was generated from the following files:
/home/rhys/Work/cppTutorial/mpagspp6/pp6calculator.git/PP6Lib/FourVector.hpp
/home/rhys/Work/cppTutorial/mpagspp6/pp6calculator.git/PP6Lib/FourVector.cpp