pp6calculator: PP6Lib/PP6Math.hpp File Reference
PP6Math.hpp File Reference
PP6 Maths Library.
#include <vector>
Functions
void swap (double &number1, double &number2)
Swap Two Numbers.
void swap (int &number1, int &number2)
Swap two ints.
bool bubbleSort (double *array, int size)
Simple bubble sort.
bool bubbleSort (double *array, int *results, int size)
Bubble sort with sepperate results.
bool bubbleSort (std::vector< double > &array)
Bubble sort for std::vector.
double multiply (double number1, double number2)
Multiply two doubles.
double divide (double number1, double number2)
Divide two numbers.
double addition (double number1, double number2)
Add two numbers.
double subtraction (double number1, double number2)
Subtract two Numbers.
double solveXaxis (double m, double c)
Solve x axis.
double solveQuadraticP (double a, double b, double c)
Solve Quadratic equation with positive descriminant.
double solveQuadraticN (double a, double b, double c)
Solve Quadratic equation with negetive descriminant.
bool solveQuadratic (double a, double b, double c, double &result1, double &result2)
Solve Quadratic.
double vectorLength3 (double i, double j, double k)
Calculate the length of a 3 vector.
double vectorDotProductSqrt4 (double a0, double a1, double a2, double a3, double b0, double b1, double b2, double b3)
Madnitude of two four vectors.
double vectorDotProduct4 (double a0, double a1, double a2, double a3, double b0, double b1, double b2, double b3)
Madnitude of two four vectors.
bool doubleZeroCheck (double number)
Check if a double is zero.
double invarientMass (double E1, double px1, double py1, double pz1, double E2, double px2, double py2, double pz2)
Calculate invarient mass squared.
int generateMuons (int numberOfMuons, double *E, double *px, double *py, double *pz)
Generate Muons.
int fourVectorZBoost (double &a0, double &a3, double vz)
Boost the components along the Z axis.
double lorentzGamma (double v)
Lorentz Gamma.
double interval (double a0, double a1, double a2, double a3)
Calculate interval of a four vector.
bool doubleCompare (const double &a, const double &b)
Double Conpare.
Detailed Description
PP6 Maths Library.
A Library to provide mathamatical functions for the pp6calculator
Definition in file PP6Math.hpp.
Function Documentation
double addition (double number1, double number2)
Add two numbers.
Parameters
number1
number2
Returns
summation result
Definition at line 106 of file PP6Math.cpp.
 {
     return number1 + number2;
 }
bool bubbleSort (double * array, int size)
Simple bubble sort.
Sorts the given array highest to lowest
Parameters
array Array to sort
size length of the array
Returns
Success boolean
Definition at line 27 of file PP6Math.cpp.
References swap().
 {
     //list starts unsorted
     bool sorted = false;
     while(!sorted){
         //see if we needed a swap this itteration
         bool swapNeeded = false;
         for (int i = 0; i < (size -1); ++i)
         {
             //if a number is small than its neighbor to the right swap them
             if (array[i] < array[i+1])
             {
                 swap(array[i], array[i+1]);
                 swapNeeded = true;
             }
         }
         //if no swaps were needed the list is now soted and the while can finish
         sorted = !swapNeeded;
     }
     return sorted;
 }
bool bubbleSort (double * array, int * results, int size)
Bubble sort with sepperate results.
Provides a sort of the given array but records the result in the results array leaving the origonal array untouched.
The results array wil be filled with the index of the element from unsorted array which should be at this position. i.e. the sorted result is
array[results[i]]
Parameters
array Array to be sorted
results Array to fill with the results.
size length of the array
Returns
Success boolean
Definition at line 51 of file PP6Math.cpp.
References swap().
 {
     bool sorted = false;
     for (int i = 0; i < size; ++i)
     {
         results[i] = i;
     }
     while(!sorted){
         bool swapNeeded = false;
         for (int i = 0; i < (size -1); ++i)
         {
             if (array[results[i]] < array[results[i+1]])
             {
                 swap(results[i], results[i+1]);
                 swapNeeded = true;
             }
         }
         sorted = !swapNeeded;
     }
     return sorted;
 }
bool bubbleSort (std::vector< double > & array)
Bubble sort for std::vector.
Sort vector passed by refference
Parameters
array Input vector
Returns
Success boolean
Definition at line 75 of file PP6Math.cpp.
References swap().
 {
     bool sorted = false;
     while(!sorted){
         bool swapNeeded = false;
         for (unsigned int i = 0; i < (array.size() -1); ++i)
         //unsigned int used to suppress compiler warnings
         {
             if (array[i] < array[i+1])
             {
                 swap(array[i], array[i+1]);
                 swapNeeded = true;
             }
         }
         sorted = !swapNeeded;
     }
     return sorted;
 }
double divide (double number1, double number2)
Divide two numbers.
Parameters
number1
number2
Returns
Divided number
Definition at line 101 of file PP6Math.cpp.
 {
     return number1 / number2;
 }
bool doubleCompare (const double & a, const double & b)
Double Conpare.
Perform a sensible equality comparison on two doubles taking account for relative erro
Parameters
a lhs double
b rhs double
Returns
true if equal
Definition at line 224 of file PP6Math.cpp.
 {
     if (a == b)
     {
         return true;
     }
     double error = fabs(a-b)/ (a > b ? a :b);
     if (error <= DBL_EPSILON)
     {
         return true;
     }
     return false;
 }
bool doubleZeroCheck (double number)
Check if a double is zero.
Performs a sensible check if a double is zero
Parameters
number number to check
Returns
true if zero, false otherwise
Definition at line 166 of file PP6Math.cpp.
 {
     if ( (fabs(number - 0.0)) <=  DBL_EPSILON)
     {
         //number is probably 0
         return true;
     }else{
         return false;
     }
 }
int fourVectorZBoost (double & a0, double & a3, double vz)
Boost the components along the Z axis.
Calculate the boosted values along the z axis for a four vector, using natural units C = 1
Parameters
a0 a0
a3 a3
vz z velocity of the boos
Returns
Success code (0= success)
Definition at line 202 of file PP6Math.cpp.
References lorentzGamma().
 {
      double a0Prime = lorentzGamma(vz)*(a0 - vz*a3);
     //a1 is unchanged
     //a2 is unchanged
     double a3Prime = lorentzGamma(vz)*(a3 - vz*a0);
     a0 = a0Prime;
     a3 = a3Prime;
     return 0;
 }
int generateMuons (int numberOfMuons, double * E, double * px, double * py, double * pz)
Generate Muons.
Generates a list of muons with random momenta and an energy based on the random momenta and the muon mass. Units of GeV.
Parameters
numberOfMuons Number of muons to generate
E Array to fill with energies
px Array to fill with px
py Array to fill with py
pz Array to fill with pz
Returns
Success code (0 = success)
Definition at line 184 of file PP6Math.cpp.
 {
     /* initialize random seed: */
     srand (time(NULL));
     for (int muon = 0; muon < numberOfMuons; ++muon)
     {
         double muonMass = 0.1057; // Muon Mass GeV
         //generate an on shell muon with random momentum
         px[muon] = (rand()%2000 -1000)*0.001;
         py[muon] = (rand()%2000 -1000)*0.001;
         pz[muon] = (rand()%2000 -1000)*0.001;
         //in natural unit E^2 = m^2 + p^2
         E[muon] = sqrt(muonMass*muonMass + px[muon]*px[muon] + py[muon]*py[muon] + pz[muon]*pz[muon]);
     }
     return 0;
 }
double interval (double a0, double a1, double a2, double a3)
Calculate interval of a four vector.
Parameters
a0 a0
a1 a1
a2 a2
a3 a3
Returns
interval squared
Definition at line 219 of file PP6Math.cpp.
References vectorDotProduct4().
 {
     return vectorDotProduct4(a0,a1,a2,a3,a0,a1,a2,a3);
 }
double invarientMass (double E1, double px1, double py1, double pz1, double E2, double px2, double py2, double pz2)
Calculate invarient mass squared.
Calculates \(m^2 \) for the momentum 4-vectors of two particles
Parameters
E1
px1
py1
pz1
E2
px2
py2
pz2
Returns
m^2
Definition at line 177 of file PP6Math.cpp.
 {
     double m2 = 0;
     m2 = (E1 + E2)*(E1 + E2) - (px1+px2)*(px1+px2) - (py1+py2)*(py1+py2) - (pz1+pz2)*(pz1+pz2);
     return m2;
 }
double lorentzGamma (double v)
Lorentz Gamma.
Gamma function for use in reletivistic calculations. \(\frac{1}{\sqrt{1-\frac{v}{c}^2}}\)
Parameters
v velocity
Returns
gamma
Definition at line 214 of file PP6Math.cpp.
 {
     return 1.0/(sqrt(1-(v/1)*(v/1)));
 }
double multiply (double number1, double number2)
Multiply two doubles.
Parameters
number1
number2
Returns
result of multiplication
Definition at line 96 of file PP6Math.cpp.
 {
     return number1 * number2;
 }
bool solveQuadratic (double a, double b, double c, double & result1, double & result2)
Solve Quadratic.
Apply the quadratic formular to solve a quadratic equation of the for \(y = ax^2 + bx + c \)
In general there are two parameters to such equations which are atributed to the two result variables passed by refference.
Parameters
a a parameter
b b parameter
c c parameter
result1 First solution
result2 Second solution
Returns
Success boolean
Definition at line 135 of file PP6Math.cpp.
References solveQuadraticN(), and solveQuadraticP().
 {
     if ((b*b-4*a*c) < 0)
     {
         return false;
     }else{
         result1 = solveQuadraticP(a,b,c);
         result2 = solveQuadraticN(a,b,c);
         return true;
     }
 }
double solveQuadraticN (double a, double b, double c)
Solve Quadratic equation with negetive descriminant.
uses the equation \(\frac{-b - \sqrt{b^2 - 4ac}}{2a} \)
Parameters
a
b
c
Returns
solution
Definition at line 129 of file PP6Math.cpp.
 {
     //find the negetive solution for a quadratic
     return (-b - sqrt(b*b - 4*a*c))/(2*a);
 }
double solveQuadraticP (double a, double b, double c)
Solve Quadratic equation with positive descriminant.
used the equation \(\frac{-b + \sqrt{b^2 - 4ac}}{2a} \)
Parameters
a
b
c
Returns
solution
Definition at line 123 of file PP6Math.cpp.
 {
     //find the positive solution for a quadratic
     return (-b + sqrt(b*b - 4*a*c))/(2*a);
 }
double solveXaxis (double m, double c)
Solve x axis.
Find the point where a given line, characterised by the equation \(y = mx + c\) crosses the x axis
Parameters
m Gradient
c Y intercept
Returns
X intercept
Definition at line 116 of file PP6Math.cpp.
 {
     // y = mc + c @y=0
     // x = -c/m
     return -c / m;
 }
double subtraction (double number1, double number2)
Subtract two Numbers.
Parameters
number1
number2
Returns
subtraction result
Definition at line 111 of file PP6Math.cpp.
 {
     return number1 - number2;
 }
void swap (double & number1, double & number2)
Swap Two Numbers.
Sipmle swap algorithm to swap two numbers
Parameters
number1
number2
Definition at line 13 of file PP6Math.cpp.
 {
     double temp = number1;
     number1 = number2;
     number2 = temp;
 }
void swap (int & number1, int & number2)
Swap two ints.
Parameters
number1
number2
Definition at line 20 of file PP6Math.cpp.
 {
     int temp = number1;
     number1 = number2;
     number2 = temp;
 }
double vectorDotProduct4 (double a0, double a1, double a2, double a3, double b0, double b1, double b2, double b3)
Madnitude of two four vectors.
Returns the dot product of two 4-vectors
Parameters
a0
a1
a2
a3
b0
b1
b2
b3
Returns
length
Definition at line 159 of file PP6Math.cpp.
 {
     return ( a0*b0 - a1*b1 -a2*b2 - a3*b3);
 }
double vectorDotProductSqrt4 (double a0, double a1, double a2, double a3, double b0, double b1, double b2, double b3)
Madnitude of two four vectors.
Returns the sqrt of the dot product of two 4-vectors
Parameters
a0
a1
a2
a3
b0
b1
b2
b3
Returns
length
Definition at line 153 of file PP6Math.cpp.
References vectorDotProduct4().
 {
     //calculate the dot product between two four vectors a and b then square root it
     return sqrt(std::abs( vectorDotProduct4(a0,a1,a2,a3,b0,b1,b2,b3)));
 }
double vectorLength3 (double i, double j, double k)
Calculate the length of a 3 vector.
returns the modulus of a 3 vector
Parameters
i
j
k
Returns
length
Definition at line 148 of file PP6Math.cpp.
 {
     return sqrt(i*i+j*j+k*k);
 }