pp6calculator: /home/rhys/Work/cppTutorial/mpagspp6/pp6calculator.git/PP6Menu/topMenu.hpp File Reference
topMenu.hpp File Reference
Top menu of pp6 calculator.
Functions
int topMenu ()
Top menu.
void topMenuPrintHelp ()
Print the help message for the top menu.
Detailed Description
Top menu of pp6 calculator.
Contains topMenu() which is the top level loop of the menu system
Definition in file topMenu.hpp.
Function Documentation
int topMenu ()
Top menu.
top level loop of the menu system allows the user to select lower teir menus
Returns
Error code
Definition at line 10 of file topMenu.cpp.
References topMenuPrintHelp(), weekOneMenu(), weekThreeMenu(), and weekTwoMenu().
 {
     int err = 0;
     topMenuPrintHelp();
     while(true){
         std::cout << "Which menu would you like? (help to show available menus) " << std::endl;
         std::cout << ": ";
         std::string opperation;
         std::cin >> opperation;
         //fail in input is broken
         if (!std::cin)
         {
             std::cin.clear();
             std::cin.ignore(INT_MAX, '\n');
             err = 2;
             continue;
         }
         if (opperation == "1" || opperation == "weekone")
         {
             err = weekOneMenu();
         }else if (opperation == "2" || opperation == "weektwo")
         {
             err = weekTwoMenu();
         }else if (opperation == "3" || opperation == "weekthree")
         {
             err = weekThreeMenu();
         }else if (opperation == "help" || opperation == "h")
         {
             //help statement
             topMenuPrintHelp();
         }else if (opperation == "quit" || opperation == "q")
         {
             return err;
         }else{
             std::cout << "Operator not recognised"<<std::endl;
             err = 2;
             continue;
         }
     }
 }